### ISSUE TITLE
Avoid synchronous JavaScript operations?

### ISSUE THREAD

**Issue by saucisson** [daurnimator/lua.vm.js#25]
The [`load_lua_over_http`](https://github.com/kripken/lua.vm.js/blob/master/src/js.lua) function makes a synchronous call to `XMLHttpRequest`. As it is considered as a bad practice, an asynchronous call could be preferred.

[This example](https://gist.github.com/saucisson/c29982abeb75c0d7342e) shows how the usual imperative style of Lua can be used together with JavaScript's callbacks. This solution does not handle well errors. It also requires that the main Lua code is executed within a coroutine. This could be done automatically by `L.execute`, for instance.

**Warning:** using coroutines within coroutines in Lua can lead to wrong behavior (from the programmer's point of view). If a JavaScript  asynchronous operation does a `yield` within a coroutine implemented iterator, the `yield` will be caught by the iterator instead of the main function. [Philipp Janda](https://github.com/siffiejoe) and i have proposed a workaround in [lua-coronest](https://github.com/saucisson/lua-coronest).

**Comment by daurnimator** [comment]
You need to use a synchronous XHR so that you can write normal looking lua code.
It's considered bad practice in the Javascript world; but we're a little bit different :)

In an ideal word. we write some sort of preloader (which sets of many requires at once and fills in `package.preload`). But I'd still have `require` as it is so that dynamic code works.

Alternatively, we could run all lua code inside of a coroutine; so that you can yield from the 'main' thread.
